---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: maven-pvc
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain  