---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: "quarkus-app-push-listener"
spec:
  triggers:
    - name: github-listener
      interceptors:
        - ref:
            name: github
            kind: ClusterInterceptor
            apiVersion: triggers.tekton.dev
          params:
            - name: eventTypes
              value:
                - push
      bindings:
        - kind: TriggerBinding
          ref: "ci-trigger-binding"
      template:
        ref: "quarkus-app-trigger-template"
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: "ci-trigger-binding"
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  params:
  - name: gitRepositoryUrl
    value: $(body.repository.clone_url)
  - name: gitRevision
    value: $(body.after)
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: "quarkus-app-trigger-template"
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  params:
  - name: gitRepositoryUrl
  - name: gitRevision
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: "ci-quarkus-app-"
      namespace: sk-workshop-components
      labels:
        app.kubernetes.io/instance: ci-pipeline
        tekton.dev/pipeline: ci-pipeline
    spec:
      params:
        - name: APP_NAME
          value: quarkus-app
        - name: ENV
          value: dev
        - name: APP_REPO_URL
          value: $(tt.params.gitRepositoryUrl)
        - name: APP_REPO_NAME
          value: application-source
        - name: APP_GIT_REVISION
          value: $(tt.params.gitRevision)
        - name: DEPLOY_REPO_URL
        # TODO: use @ and modify it during repo clone
          value: http://gitea.sk-workshop-components.svc:3000
        - name: DEPLOY_REPO_OWNER
          value: gitea
        - name: DEPLOY_REPO_NAME
          value: application-deploy
        - name: REGISTRY
          value: image-registry.openshift-image-registry.svc:5000/sk-app-dev
      pipelineRef:
        name: ci-pipeline
      serviceAccountName: pipeline
      timeout: 1h0m0s
      workspaces:
        # TODO: template + cronjob
        - name: app-source
          persistentVolumeClaim:
            claimName: "source-pvc"
        - name: maven-settings
          emptyDir: {}
