apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: quarkus-app
  namespace: openshift-gitops
  # ONLY if you want these to cascade delete
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: http://gitea.sk-workshop-components.svc.cluster.local:3000/gitea/application-deploy.git
    targetRevision: master
    path: argo/app-sets
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-gitops
  syncPolicy:
    automated: {}
