---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: quarkus-app
  annotations:
    # The event we are targeting as seen from the webhook payload
    # this can be an array too, i.e: [pull_request, push]
    pipelinesascode.tekton.dev/on-event: "[pull_request, push]"

    # The branch or tag we are targeting (ie: main, refs/tags/*)
    pipelinesascode.tekton.dev/on-target-branch: "[main]"

    # Fetch the git-clone task from hub, we are able to reference later on it
    # with taskRef and it will automatically be embedded into our pipeline.
    #pipelinesascode.tekton.dev/task: "git-clone"
    pipelinesascode.tekton.dev/task: "https://github.com/skoussou/tekton-catalog/blob/main/ci-tasks/resources/git-clone-custom/0.1/git-clone.yaml"

    # Use maven task from the hub to test our Java project
    pipelinesascode.tekton.dev/task-1: "maven"
   
    # You can add more tasks by increasing the suffix number, you can specify
    # them as array to have multiple of them.
    # browse the tasks you want to include from hub on https://hub.tekton.dev/
    #
    # pipelinesascode.tekton.dev/task-2: "[curl, buildah]"
    pipelinesascode.tekton.dev/task-2: "https://github.com/skoussou/tekton-catalog/blob/main/ci-tasks/resources/task-generate-version/0.1/task-generate-version.yaml"
    pipelinesascode.tekton.dev/task-3: "https://github.com/skoussou/tekton-catalog/blob/main/ci-tasks/resources/mock/0.1/task-mock.yaml"    
    pipelinesascode.tekton.dev/task-4: "https://github.com/skoussou/tekton-catalog/blob/main/ci-tasks/resources/s2i-java-custom/0.1/s2i-java.yaml"    
    pipelinesascode.tekton.dev/task-5: "https://github.com/skoussou/tekton-catalog/blob/main/ci-tasks/resources/task-tag-image/0.1/task-tag-image.yaml"    
    pipelinesascode.tekton.dev/task-6: "https://github.com/skoussou/tekton-catalog/blob/main/ci-tasks/resources/task-create-pr-to-deploy/0.1/task-create-pr-to-deploy.yaml"        

    # How many runs we want to keep attached to this event
    pipelinesascode.tekton.dev/max-keep-runs: "5"

    # Executes only for specific paths
    pipelinesascode.tekton.dev/on-cel-expression: |
      event == "push" && "pom.xml".pathChanged() 

spec:
  params:
    # The variable with brackets are special to Pipelines as Code
    # They will automatically be expanded with the events from Github.
    - name: repo_url
      value: "{{ repo_url }}"
    - name: revision
      value: "{{ revision }}"
    # The variable with brackets are special to Pipelines as Code
    # They will automatically be expanded with the events from Github.
    - name: APP_NAME
      value: quarkus-app
    - name: ENV
      value: string
      default: dev
    - name: APP_REPO_URL
      value: "{{ repo_url }}"
    - name: APP_REPO_NAME
      value: string
    - name: APP_GIT_REVISION
      value: "{{ revision }}"
    - name: DEPLOY_REPO_URL
      value: http://gitea.sk-workshop-components.svc:3000
    - name: DEPLOY_REPO_OWNER
      value: gitea
    - name: DEPLOY_REPO_NAME
      value: application-deploy
    - name: REGISTRY
      value: image-registry.openshift-image-registry.svc:5000/sk-app-dev
    - name: CI_NS_PREFIX
      value: sk         
  pipelineSpec:
    params:
      - name: repo_url
      - name: revision
    workspaces:
      - name: app-source      
    tasks:
      # ------------ CLONE APP SOURCE ------------ #
      - name: git-app-clone
        taskRef:
          name: git-clone-custom
        params:
          - name: url
            value: $(params.APP_REPO_URL)
          - name: revision
            value: $(params.APP_GIT_REVISION)
          - name: deleteExisting
            value: 'true'
          - name: subdirectory
            value: $(params.APP_REPO_NAME)
        workspaces:
          - name: output
            workspace: app-source
      # ------------ GENERATE VERSION ------------ #
      - name: generate-version
        runAfter:
          - git-app-clone
        taskRef:
          name: generate-version
        params:
          - name: APP_NAME
            value: $(params.APP_REPO_NAME)
        workspaces:
          - name: source
            workspace: app-source
      # ------------ UNIT TEST ------------ #
      # - name: mvn-config
      #   taskRef: 
      #     name: mvn-config
      #   runAfter:
      #     - fetch-repository
      #   workspaces:
      #   - name: workspace
      #     workspace: source
      - name: unit-test
        taskRef:
          name: maven
        runAfter:
          - generate-version
        taskRef:
          name: mock
        params:
          - name: MOCK_MSG
            value: unit-test        
#        params:
#          - name: CONTEXT_DIR
#            value: $(params.APP_REPO_NAME)
#          - name: GOALS
#            value:
#              - clean
#              - test
#        workspaces:
#        - name: source
#          workspace: app-source
#        - name: maven-settings
#          workspace: maven-settings
      # ------------ CODE ANALYSIS ------------ #
      - name: code-analysis
        runAfter:
          - generate-version
        taskRef:
          name: mock
        params:
          - name: MOCK_MSG
            value: code-analysis
      # ------------ DEPENDENCY CHECK ------------ #
      - name: dependency-check
        runAfter:
          - generate-version
        taskRef:
          name: mock
        params:
          - name: MOCK_MSG
            value: dependency-check
      # ------------ PACKAGE APP ------------ #
      - name: package-app
        runAfter:
          - dependency-check
          - code-analysis
          - unit-test
        taskRef:
          name: mock
        params:
          - name: MOCK_MSG
            value: package-app
      # ------------ NEXUS UPLOAD ------------ #
      - name: nexus-upload
        runAfter:
          - package-app
        taskRef:
          name: mock
        params:
          - name: MOCK_MSG
            value: nexus-upload
      # ------------ BUILD IMAGE ------------ #
      - name: build-image
        runAfter:
          - nexus-upload
        taskRef:
          kind: ClusterTask
          name: s2i-java       
        params:
          - name: IMAGE
            value: $(params.REGISTRY)/$(params.APP_NAME)
          - name: PATH_CONTEXT
            value: $(params.APP_REPO_NAME)
        workspaces:
          - name: source
            workspace: app-source
      # ------------ IMAGE SCAN ------------ #
      - name: image-scan
        runAfter:
          - build-image
        taskRef:
          name: mock
        params:
          - name: MOCK_MSG
            value: image-scan
      # ------------ IMAGE CHECK ------------ #
      - name: image-check
        runAfter:
          - build-image
        taskRef:
          name: mock
        params:
          - name: MOCK_MSG
            value: image-check
      # ------------ TAG IMAGE ------------ #
      - name: tag-image
        runAfter:
          - image-check
          - image-scan
        taskRef:
          name: tag-image
        params:
          - name: IMAGE
            value: $(params.CI_NS_PREFIX)-app-dev/$(params.APP_NAME)
          - name: IMAGE_TAG
            value: latest
          - name: IMAGE_NEW_TAG
            value: "$(tasks.generate-version.results.version)"            
      # ------------ CREATE PR ------------ #
      - name: create-pr-to-deploy
        runAfter:
          - tag-image
        taskRef:
          name: create-pr-to-deploy
        params:
          - name: DEPLOY_REPO_URL
            value: $(params.DEPLOY_REPO_URL)
          - name: DEPLOY_REPO_OWNER
            value: $(params.DEPLOY_REPO_OWNER)
          - name: DEPLOY_REPO_NAME
            value: $(params.DEPLOY_REPO_NAME)
          - name: BRANCH_NAME
            value: $(params.ENV)-image-$(tasks.generate-version.results.version)
          - name: IMAGE_NAME
            value: $(params.APP_NAME)
          - name: IMAGE_URL
            value: $(params.REGISTRY)/$(params.APP_NAME)
          - name: IMAGE_NEW_VERSION
            value: $(tasks.generate-version.results.version)
          - name: ENV
            value: $(params.ENV)
          - name: PR_BODY
            value: |
              application: $(params.APP_NAME)\nmessage: 'New image for $(params.ENV) environment'\napplicationRepo: $(params.APP_REPO_URL)\napplicationRevision: $(params.APP_GIT_REVISION)\nimage: $(params.REGISTRY)/$(params.APP_NAME)\nversion: $(tasks.generate-version.results.version)\ndeployRepo: $(params.DEPLOY_REPO_URL)\ndeployOwner: $(params.DEPLOY_REPO_OWNER)\ndeployName: $(params.DEPLOY_REPO_NAME)\nenvironment: $(params.ENV)               
        workspaces:
          - name: source
            workspace: app-source              
#      - name: build-native-executable
#        params:
#          - name: GOALS
#            value:
#              - '-DskipTests'
#              - package
#              - '-Dquarkus.native.container-build=true'
#          - name: CONTEXT_DIR
#            value: $(params.APP_REPO_NAME)
#        runAfter:
#          - maven-test
#        taskRef:
#          kind: ClusterTask
#          name: maven
#        workspaces:
#          - name: source
#            workspace: app-source
#          - name: maven-settings
#            workspace: maven-settings
            
            
  workspaces:
    - name: maven-settings
      workspace: maven-settings
      persistentVolumeClaim:
        claimName: "maven-pvc"  
    - name: app-source
      workspace: app-source
      persistentVolumeClaim:
        claimName: "source-pvc"        
