apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshift-gitops-operator
spec:
  channel: gitops-1.5
  installPlanApproval: Automatic
  name: openshift-gitops-operator
  source: redhat-operators 
  sourceNamespace: openshift-marketplace 